### PR TITLE
Pre-compile regular expressions before being used

### PR DESCRIPTION
**Pull request by mattrobenolt**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
damn

**Comment by bryanhelmig** [comment]
Yeah, this seemed like a decent patch. Any reason for the close instead of the merge?

Setting aside the fact that we haven't paid attention to this package for ... oh, 3 years ... 👀

**Comment by roycehaynes** [comment]
@mattrobenolt - To be fair, this is a decent patch looking at the PR. Definitely worthy of reopen and merge....

**Comment by roycehaynes** [comment]
@mattrobenolt  6 tests failed after merge (should have ran locally before merging). Looking at this now, but may want to give your impl a second peep.

**Comment by roycehaynes** [comment]
You can run tests by python from root dir `python tests/test_email_reply_parser.py`

**Comment by kageurufu** [comment]
Python caches compiled regex regardless the first time they are compiled or used, unless this adds something on top of that I didn't see it as that important.

This will, however, potentially save a function call and dictionary lookup in practice

**Pull request merged**
